### ISSUE TITLE
getHistory api issue

### ISSUE THREAD

**Issue by altbee** [bonustrack/obyte.js#76]
### Expected behavior
const params = {
  witnesses: witnesses,
  addresses: ['ULQA63NGEZACP4N7ZMBUBISH6ZTCUS2Q']
};

When I call getHistory api with correct witnesses and wrong address, I think I should get empty response or error response.
### Actual behavior
But it doesn't get any response.

**Comment by tarmo888** [comment]
What do you mean by wrong address? I am unable to reproduce your error.
I think the problem is not in address, but because your connection closed.

Use `reconnect` option or send `heartbeat in every 10 seconds https://obytejs.com/utils/keep-connection-alive
